### ISSUE TITLE
ClusterSharedVolume

### ISSUE THREAD

**Issue by donatofurio** [ColiseoSoftware/hypervbackup#4] opened 2016-02-08 16:38 UTC
HI!
Great work!
is possible to add the ClusterSharedVolume support like the original project?
i'm not so able in programming to do it myself.
thanks!

**Comment by pablopioli** [comment] 2016-02-15 12:18
The problem is I don't have a CSV to test if it really works.
If someone offers to be a beta tester and checks that HyperVBackup works correctly from a CSV I will add it again. But it has to be a responsible offer and test it in a real environment.

**Comment by donatofurio** [comment] 2016-02-15 12:52
I can test it in my cluster on hyperv server 2012, soon i can test on
hyperv server 2008. And hope to do a test on 2012 r2
Il 15/Feb/2016 13:18, "pablopioli" notifications@github.com ha scritto:

**Comment by donatofurio** [comment] 2016-03-08 11:36
I can do tests even on hyper-v Server 2016 (t.p.) at the end of the month

**Comment by Jimshark** [comment] 2016-03-09 01:16
Hi, great job folkes ! I have a pre-production 2012 R2 2 Nodes Cluster with CSV (SAS SAN). I can help testing the Beta HVBackup on CSV. I use it with 7z.dll quite extensively. If you would send me a compiled version. Thanks

**Comment by pablopioli** [comment] 2016-03-13 13:23
OK, give a couple of weeks, March is being a lot more busy than what I expected

**Comment by Jimshark** [comment] 2016-03-15 00:39
Hi Pablo, thanks for your answer. No problem at all. Feel free get back to us when you have more spare time. ;-)

**Comment by Jimshark** [comment] 2016-04-08 06:27
Hi Guys, i have HVBackup 101 OK on my 2 Nodes 2012R2 cluster in production. I used a modified HVBackuplaunch script with Get VM piping. Compression 0 for now because this version is slow. Will be happy to test the new one with 7z. Cheers

**Comment by pablopioli** [comment] 2016-04-12 21:49
Sorry for have you waiting, a lot of (other) work ...

As I said I have no CSV cluster to test this, so I added the original code, and now it's up to you:

https://onedrive.live.com/redir?resid=6DBCDBD8B6418012!869728&authkey=!ANFYiKKEXp61ahE&ithint=file%2c7z

If it works correctly I will compile a release.

**Comment by donatofurio** [comment] 2016-04-12 22:11
I will test it in few days... a log of work alzò for me in these
days(fortunately)
Il 12/apr/2016 23:49, "pablopioli" notifications@github.com ha scritto:

**Comment by Jimshark** [comment] 2016-04-14 03:33
Hi Pablo, 
Thank you so much for your work, i just tested the 2.1 beta on a 2012 R2 VM on a 2012 R2 Cluster with SAN CSV. Works great. :-)
v1.01    15,8Gb     00:17:38  Compression 0   zip
v2.1b      7,6Gb        00:06:01  Compression 1   7z
All VM's programmed to backup on the 2 nodes for tonight.
We keep in touch

**Comment by donatofurio** [comment] 2016-04-14 10:18
Ho Paolo! I've tried this morning in 10 minutes and get an error, sorry but
no time to write with error. May be that my lack in programming makes some
mistakes in compiling. Can u send me a compiled version or Jim can u share
your  so I can rest on 2012. yet installed .net 4.6 and c++. Thanks to all
Donato
Il 14/apr/2016 05:33, "Jimshark" notifications@github.com ha scritto:

**Comment by pablopioli** [comment] 2016-04-14 13:18
> Hi Pablo, 
> Thank you so much for your work, i just tested the 2.1 beta on a 2012 R2 VM on a 2012 R2 Cluster with SAN CSV. Works great. :-)

Good to hear it, if everything goes this way I will publish a new release before the end of the month.

**Comment by pablopioli** [comment] 2016-04-14 13:20
> Ho Paolo! I've tried this morning in 10 minutes and get an error, sorry but no time to write with error. May be that my lack in programming makes some mistakes in compiling. Can u send me a compiled version or Jim can u share your so I can rest on 2012. yet installed .net 4.6 and c++. Thanks to all Donato

The best way to no forget anything would be to download the latest release and replace the two updated files with those in OneDrive. Try it and post the error you have.
A better logging would be interesting for the next version.

**Comment by donatofurio** [comment] 2016-04-14 15:07
C:\Script\HVBackup>HyperVBackup.exe -o c:\temp --compressionlevel 0
HyperVBackup 2.1
Copyright (C) 2012 Cloudbase Solutions Srl
Copyright (C) 2016 Coliseo Software Srl

Error: Il valore non può essere null.
Nome parametro: source
   in System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   in HyperVBackup.Console.Program.Main(String[] args)

C:\Script\HVBackup>HyperVBackup.exe -o c:\temp --compressionlevel 0

Eccezione non gestita: System.IO.FileNotFoundException: Impossibile
caricare il
file o l'assembly 'CommandLine, Version=1.9.71.2, Culture=neutral,
PublicKeyToke
n=de6f01bd326f8c32' o una delle relative dipendenze. Impossibile trovare il
file
 specificato.
   in HyperVBackup.Console.Program.Main(String[] args)

this is the error

2016-04-14 15:20 GMT+02:00 pablopioli notifications@github.com:

> Ho Paolo! I've tried this morning in 10 minutes and get an error, sorry
> but no time to write with error. May be that my lack in programming makes
> some mistakes in compiling. Can u send me a compiled version or Jim can u
> share your so I can rest on 2012. yet installed .net 4.6 and c++. Thanks to
> all Donato
> 
> The best way to no forget anything would be to download the latest release
> and replace the two updated files with thoso in OneDrive. Try it and post
> the error you have.
> A better logging would be interesting for the next version.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ColiseoSoftware/hypervbackup/issues/4#issuecomment-209938111

## 

Donato Furio

___________________________________________________________________________________

DNA SERVIZI INFORMATICI SRL   VIA CADUTI DELLA LIBERTA',30  40043
MARZABOTTO (BO) TEL 051-6787143  FAX 051-6780154 WWW.DNASERVIZI.COM
http://www.dnaservizi.com/
___________________________________________________________________________________

Questo messaggio di posta elettronica contiene informazioni di carattere
confidenziale rivolte esclusivamente al destinatario sopra indicato. E'
vietato l'uso, la diffusione, distribuzione o riproduzione da parte di ogni
altra persona. Nel caso aveste ricevuto questo messaggio di posta
elettronica per errore, siete pregati di segnalarlo immediatamente al
mittente e distruggere quanto ricevuto (compresi i file allegati) senza
farne copia. Qualsivoglia utilizzo non autorizzato del contenuto di questo
messaggio costituisce violazione dell'obbligo di non prendere cognizione
della corrispondenza tra altri soggetti, salvo più grave illecito, ed
espone il responsabile alle relative conseguenze.

**Comment by pablopioli** [comment] 2016-04-14 18:07
https://onedrive.live.com/redir?resid=6DBCDBD8B6418012!871492&authkey=!AMS6MemOcYjhRUQ&ithint=file%2c7z

This is the complete set of files. Check if you have problems with .net 4.6

**Comment by Jimshark** [comment] 2016-04-14 21:27
Hi guys,
I already had 101 installed.
I took the 2.1 last release and replaced the files 
I replaced the 2 updated files from Pablo's Onedrive
I installed Package redistribuable de Microsoft Visual C++ 2010 SP1 (x64) : vcredist_x64.exe
No use of .Net 4.6 with 2012 R2 that's what the install process said !
Node 2:
2003 R2 1       7,4Gb       00:06:08
2003 R2 2       47,7Gb      00:23:11
Debian 8            30,4Gb      00:15:57
2012 R2         7,6Gb       00:05:58
I just had a file system error on the Debian VM but i think this is due to VSS compatibility and had
already the same error sometimes with 101.
Compression 1 gives around 35% compression ratio.
Will test on node 1 tonight with 150Gb VM.
Cheers

**Comment by bstag** [comment] 2016-04-15 13:02
Well, it worked for one machine. It seems the null error mentioned is related to not specifying a machine as in the default for all machines. I would guess it is erroring out in reading the clustered machine list. If you tell it each machine it seems to work just fine. I have one machine that is failing but I have not dug into it yet. I would bet its a normal VSS issue.

**Comment by pablopioli** [comment] 2016-04-15 14:23
Thanks for your info. Yes, it was a bug when you wanted to backup all virtual machines. It's working in this version.

https://onedrive.live.com/redir?resid=6DBCDBD8B6418012!871498&authkey=!AEQ6DUz8bXhyZJU&ithint=file%2c7z

**Comment by Jimshark** [comment] 2016-04-15 22:53
I use HVBackuplauch script that i modified for cluster to launch HyperVBackup one VM by one VM, see:
https://github.com/nelsh/HVbackupLaunch/issues/1
It has error management, e-mail reports and you can pipe to send the list of the VM.
Might me helpfull for you.

**Comment by Jimshark** [comment] 2016-04-16 01:06
Tested Beta 3 on a 2012 R2 VM on my cluster OK. 
Beta 2 01h11 138,7 Gb 3 VM Compression 1.

**Comment by donatofurio** [comment] 2016-04-18 07:14
ok!
now it WORKS! Beta 3 on 2012 cluster
i'm backuping now my VM.
works specifing machine name and without specifing it.

2016-04-16 3:06 GMT+02:00 Jimshark notifications@github.com:

> Tested Beta 3 on a 2012 R2 VM on my cluster OK.
> Beta 2 01h11 138,7 Gb 3 VM Compression 1.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ColiseoSoftware/hypervbackup/issues/4#issuecomment-210701837

## 

Donato Furio

___________________________________________________________________________________

DNA SERVIZI INFORMATICI SRL   VIA CADUTI DELLA LIBERTA',30  40043
MARZABOTTO (BO) TEL 051-6787143  FAX 051-6780154 WWW.DNASERVIZI.COM
http://www.dnaservizi.com/
___________________________________________________________________________________

Questo messaggio di posta elettronica contiene informazioni di carattere
confidenziale rivolte esclusivamente al destinatario sopra indicato. E'
vietato l'uso, la diffusione, distribuzione o riproduzione da parte di ogni
altra persona. Nel caso aveste ricevuto questo messaggio di posta
elettronica per errore, siete pregati di segnalarlo immediatamente al
mittente e distruggere quanto ricevuto (compresi i file allegati) senza
farne copia. Qualsivoglia utilizzo non autorizzato del contenuto di questo
messaggio costituisce violazione dell'obbligo di non prendere cognizione
della corrispondenza tra altri soggetti, salvo più grave illecito, ed
espone il responsabile alle relative conseguenze.

**Comment by donatofurio** [comment] 2016-04-21 10:42
some Tests:
Compression 0 - time 2:01:07 file size 232.6 Gb
Compression 1 - time 2:12:17 file size 171.2 Gb
tring with compression 2 but out of space......but this is the error, may be usefull  if the program says "out of space"

C:\Script\HVBackup>HyperVBackup.exe  -o d: --compressionlevel 2
HyperVBackup 2.2
Copyright (C) 2012 Cloudbase Solutions Srl
Copyright (C) 2016 Coliseo Software Srl

Backing up all VMs on this server
Initializing VSS

Starting snapshot set for:
Backup Using Child Partition Snapshot\DNAS01

Volumes:
C:\ClusterStorage\volume1\

Component: "Backup Using Child Partition Snapshot\DNAS01"
Archive: "macchine virtuali\DNAS01.vhdx"
...................................Error: The execution has failed due to the bug in the SevenZipSharp.
Please report about it to http://sevenzipsharp.codeplex.com/WorkItem/List.aspx,
post the release number and attach the archive.
   in SevenZip.SevenZipBase.ThrowException(CallbackBase handler, Exception[] e)
   in SevenZip.SevenZipBase.CheckedExecute(Int32 hresult, String message, CallbackBase handler)
   in SevenZip.SevenZipCompressor.CompressStreamDictionary(Dictionary`2 streamDictionary, Stream archiveStream, String password)
   in SevenZip.SevenZipCompressor.CompressStreamDictionary(Dictionary`2 streamDictionary, String archiveName, String password)
   in HyperVBackUp.Engine.BackupManager.BackupFiles(IList`1 components, IDictionary`2 volumeMap, IDictionary`2 snapshotVolumeMap, IDictionary`2 vmNamesMap, Options options)
   in HyperVBackUp.Engine.BackupManager.BackupSubset(IDictionary`2 vmNamesMapSubset, Options options)
   in HyperVBackUp.Engine.BackupManager.VssBackup(IEnumerable`1 vmNames, VmNameType nameType, Options options)
   in HyperVBackup.Console.Program.Main(String[] args)

C:\Script\HVBackup>

**Comment by donatofurio** [comment] 2016-04-22 07:15
Compression 0 - time 2:01:07 file size 232.6 Gb
Compression 1 - time 2:12:17 file size 171.2 Gb
Compression 2 - time 2:11:46 file size 171.1 Gb
Compression 6 - time 6:15:16 file size 161.8 Gb

**Comment by pablopioli** [comment] 2016-04-22 14:43
> I use HVBackuplauch script that i modified for cluster to launch HyperVBackup one VM by one VM, see:
> nelsh/HVbackupLaunch#1

I'm adding a link on the project description page as it is a useful addition.

**Comment by pablopioli** [comment] 2016-04-22 14:44
Thanks for all your feedback. As it works as expected in a few day I'll close this issue and release an official version.

**Comment by pablopioli** [comment] 2016-04-22 14:47
> tring with compression 2 but out of space......but this is the error, may be usefull if the program says "out of space"

The problem here is that the library that acts as an interface to 7zip doesn't gives a lot of info when an error happens. I've seen the same error on other conditions.
I will look at this for the next version, as basically the additions are about logging.

**Comment by pablopioli** [comment] 2016-04-22 15:22
> Compression 0 - time 2:01:07 file size 232.6 Gb
> Compression 1 - time 2:12:17 file size 171.2 Gb
> Compression 2 - time 2:11:46 file size 171.1 Gb
> Compression 6 - time 6:15:16 file size 161.8 Gb

Based on this information I will change the default compression level to 3. Is what I use for my real backups.

**Comment by Jimshark** [comment] 2016-04-26 00:52
Hi There,
VHD of 18.1Go
Compression 1   9,2Gb       00:06:29
Compression 2   9,2Gb       00:06:45
Compression 3   8,7Gb       00:07:44
All backups are running good on my cluster 2 nodes, i stay with compression 1 for i need more backup speed than backup space.
HyperVbackup HV1 to Nas1\vmbackup. Success: 3/3, Error: 0 in 01:19:42 Size: 174,9 Gb
HyperVBackup HV2 to Nas1\vmbackup. Success: 3/3, Error: 0 in 00:31:31 Size: 52,2 Gb

**Comment by donatofurio** [comment] 2016-04-26 13:40
Compression 0 - time 2:01:07 file size 232.6 Gb
Compression 1 - time 2:12:17 file size 171.2 Gb
Compression 2 - time 2:11:46 file size 171.1 Gb
Compression 3 - time 4:18:02 file size 167.6 Gb
Compression 6 - time 6:15:16 file size 161.8 Gb

compression1 or 2 seems to give moore performance

**Comment by pablopioli** [comment] 2016-05-17 04:36
Released version 2.2 with this feature included, if you were using it in production there is no need to update the program, as it is exactly the same code with another version number.

**Closed as completed by pablopioli** 2016-05-17 04:36 UTC
